site_name: 'NadekoBot'
site_url: 'https://nadeko.bot'
repo_url: 'https://gitlab.com/kwoth/nadekobot'
site_author: 'Kwoth'
nav:
- Home: index.md
- Guides:
    - Windows Guide: guides/windows-guide.md
    - Linux Guide: guides/linux-guide.md
    - OSX Guide: guides/osx-guide.md
    - From Source: guides/from-source.md
    - Docker Guide (unsupported): guides/docker-guide.md
- Commands:
    - Readme: commands-readme.md
    - Commands List: https://nadeko.bot/commands
- Features Explained:
    - Creating and inviting the bot: create-invite.md
    - JSON Explanations: jsons-explained.md
    - Permissions System: permissions-system.md
    - Custom Reactions: custom-reactions.md
    - Placeholders: placeholders.md
    - Bot Config: bce-guide.md
- Contribution Guide: contribution-guide.md
- ❤ Donate ❤: donate.md
- License: license.md
theme: 'material'